### ISSUE TITLE
Results between web validator and CLI validator do not match

### ISSUE THREAD

**Issue by dvillaveces-tq** [CMSgov/hpt-validator-cli#16]
## Issue Report

Some files are marked as 100% valid by the online validator, but not the CLI validator

### Expected behavior

I would expect the same file to give the same result on the CLI and web validator.

### Actual behavior

This [file](https://www.northwell.edu/sites/northwell.edu/files/machine-readable-files/Lenox_Hill_Hospital_StandardCharges.zip) passes the online validator (see screenshot).
![Screenshot 2024-08-07 at 4 28 52 PM](https://github.com/user-attachments/assets/ab179300-25a3-4e71-aa8d-fdd728707e88)

But the same file throws errors when using the CLI validator:
<img width="1138" alt="Screenshot 2024-08-07 at 4 30 03 PM" src="https://github.com/user-attachments/assets/ba475a93-f45d-4719-823d-954a8118965a">

Incidentally, this file actually does not seem compliant because it has `gross_charges` instead of `gross_charge`, but that does not seem to be the error the CLI gives.

### Steps to reproduce the behavior

1. Download the linked [file](https://www.northwell.edu/sites/northwell.edu/files/machine-readable-files/Lenox_Hill_Hospital_StandardCharges.zip)
2. Unzip it
3. Run it through the CLI validator using `cms-hpt-validator Lenox_Hill_Hospital_StandardCharges.json v2.0.0`
4. Run the same file through the online validator at https://cmsgov.github.io/hpt-tool/online-validator/

(Note, this time I made sure I'm using the latest version (1.0.12) of the CLI validator)

**Comment by daniel-eckel** [comment]
Thank you for raising this issue. The reason for the mismatch in results between the online validator and the CLI validator is due to the presence of a byte-order mark (BOM) at the beginning of the Lenox Hill Hospital MRF. The online validator parser automatically removes the BOM but the CLI validator parser does not, resulting in the parser error in the above screenshot. A fix to the validator core has been [coded and merged on August 19, 2024](https://github.com/CMSgov/hpt-validator/pull/53) to remove BOM from all MRFs. Reinstalling the CLI validator and rerunning the Lenox Hill Hospital File will result in matching results between the online validator and CLI validator.

Additionally, the hospital price transparency regulations allow for additional hospital defined attributes in JSON MRFs. The validator is operating as expected and treats ‘gross_charges’ as an additional hospital defined attribute. Leveraging the Validator helps ensure adherence to CMS form and manner requirements (45 CFR 180.50(c)(2)), but it does not certify that the MRF fully complies with all HPT requirements at 45 CFR 180.50.

**Comment by daniel-eckel** [comment]
Thank you for raising this issue. The reason for the mismatch in results between the online validator and the CLI validator is due to the presence of a byte-order mark (BOM) at the beginning of the Lenox Hill Hospital MRF. The online validator parser automatically removes the BOM but the CLI validator parser does not, resulting in the parser error in the above screenshot. A fix to the validator core has been [coded and merged on August 19, 2024](https://github.com/CMSgov/hpt-validator/pull/53) to remove BOM from all MRFs. Reinstalling the CLI validator and rerunning the Lenox Hill Hospital File will result in matching results between the online validator and CLI validator.

Additionally, the hospital price transparency regulations allow for additional hospital defined attributes in JSON MRFs. The validator is operating as expected and treats ‘gross_charges’ as an additional hospital defined attribute. Leveraging the Validator helps ensure adherence to CMS form and manner requirements (45 CFR 180.50(c)(2)), but it does not certify that the MRF fully complies with all HPT requirements at 45 CFR 180.50.

**Comment by daniel-eckel** [comment]
Thank you for raising this issue. The reason for the mismatch in results between the online validator and the CLI validator is due to the presence of a byte-order mark (BOM) at the beginning of the Lenox Hill Hospital MRF. The online validator parser automatically removes the BOM but the CLI validator parser does not, resulting in the parser error in the above screenshot. A fix to the validator core has been [coded and merged on August 19, 2024](https://github.com/CMSgov/hpt-validator/pull/53) to remove BOM from all MRFs. Reinstalling the CLI validator and rerunning the Lenox Hill Hospital File will result in matching results between the online validator and CLI validator.

Additionally, the hospital price transparency regulations allow for additional hospital defined attributes in JSON MRFs. The validator is operating as expected and treats ‘gross_charges’ as an additional hospital defined attribute. Leveraging the Validator helps ensure adherence to CMS form and manner requirements (45 CFR 180.50(c)(2)), but it does not certify that the MRF fully complies with all HPT requirements at 45 CFR 180.50.
